### ISSUE TITLE
[BUG] Ошибка при вводе спецсимволов в поле Название магазина на экране Добавления карты

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/odcs-frontend#273]
Шаги:
1. Авторизоваться под действующим пользователем
2. Нажать на кнопку Добавить карту на экране Мои карты
3. Ввести в поле Название магазина валидные данные (спецсимволы) - @&#()№*"?

ОР: Можно ввести спецсимволы в поле Название магазина на экране Добавления карты
ФР: Ошибка при вводе спецсимволов в поле Название магазина на экране Добавления карты

Окружение:
iOS 16.6.1, iPhone 14, 390 × 844, Safari

![photo_2023-11-28_23-16-43](https://github.com/Online-discount-card-service/odcs-frontend/assets/148253752/8e30f689-7cc5-42eb-9dad-c3697c69060e)

**Comment by kavabunga** [comment]
Актуальные требования: 
Может содержать A-Z, a-z, А-Я, а-я, Ёё, цифры, пробелы, символы @ ! # $ % & ' * + / = ? ^ _ ` { | } ~ - . 
(1-30 символов)

**Comment by RollerDi** [comment]
Не проходят `~
