### ISSUE TITLE
[BUG] Форма авторизации - пользователю не выводится сообщение об ошибке, если введен несуществующий в базе email

### ISSUE THREAD

**Issue by Xalgina** [Online-discount-card-service/odcs-frontend#293]
Шаги:

1. Перейти на https://skidivay.acceleratorpracticum.ru/
2. Нажать на кнопку "Войти"
3. Заполнить поле Email несуществующим в базе значением
4. Заполнить поле Пароль
5. Нажать на кнопку "Войти" 

ОР: поле подсвечивается красным, под полем красным цветом выводится сообщение об ошибке "Неверно указан Email"
ФР: поле не подсвечивается, ошибка не выводится, флоу блокируется - при нажатии на кнопку Войти ничего не происходит

Окружение:

- Xiaomi Redmi 9, Android 11, разрешение экрана 393x873. Google Chrome 119.0.6045.163
- iOS 16.6.1, iPhone 14, 390 × 844, Safari

![image](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/9c9683e3-fd0d-4123-bd90-d0c37bda1259)
![ФР 5](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/192458fe-14bb-49d7-b80a-2713dc698a0c)

**Comment by kavabunga** [comment]
@Xalgina @sldmxm аналогично паролю — передаю бэкам

**Comment by sldmxm** [comment]
> @Xalgina @sldmxm аналогично паролю — передаю бэкам

аналогично паролю

**Comment by sldmxm** [comment]
@Xalgina @kavabunga 
На дейли согласились, что выводить надо общую ошибку, вне зависимости от того что неверно - пароль, мейл или все сразу

**Comment by kavabunga** [comment]
Закрываем как больше не актуальное
