### ISSUE TITLE
[BUG] Форма авторизации - пользователю не выводится сообщение об ошибке, если введен пароль, который не совпадает с паролем пользователя с указанным Email

### ISSUE THREAD

**Issue by Xalgina** [Online-discount-card-service/odcs-frontend#294]
Шаги:

1. Перейти на https://skidivay.acceleratorpracticum.ru/
2. Нажать на кнопку "Войти"
3. Заполнить поле Email существующим в базе значением
4. Заполнить поле Пароль значением, не совпадающим с паролем для этого пользователя
5. Нажать на кнопку "Войти"

ОР: поле подсвечивается красным, под полем красным цветом выводится сообщение об ошибке "Введен неверный пароль"
ФР: поле не подсвечивается, ошибка не выводится, флоу блокируется - при нажатии на кнопку Войти ничего не происходит

Окружение:

Xiaomi Redmi 9, Android 11, разрешение экрана 393x873. Google Chrome 119.0.6045.163
iOS 16.6.1, iPhone 14, 390 × 844, Safari

![image](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/2eb72d96-5332-41d7-b251-45f7ad388ef8)
![image](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/0b10ac11-65fb-4ddb-92f1-2414079e2ff1)

https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/826df569-957e-4e90-94a5-88f951cea056

(в видео я тыкаю на кнопку Войти, этого почти не видно)

**Comment by kavabunga** [comment]
@Xalgina @sldmxm перекидываю к бэку. Нам в ответе эта ошибка не приходит сейчас в таком виде. Нужен текст "Введен неверный пароль" привязанный к полю password.

**Comment by sldmxm** [comment]
> @Xalgina @sldmxm перекидываю к бэку. Нам в ответе эта ошибка не приходит сейчас в таком виде. Нужен текст "Введен неверный пароль" привязанный к полю password.

С точки зрения безопасности не стоит писать, что именно неправильно - почта или пароль.
Если пишем только про пароль (или только про почту), значит, такой адрес почты у нас (не) зарегистрирован.

**Comment by sldmxm** [comment]
@Xalgina @kavabunga 
На дейли согласились, что выводить надо общую ошибку, вне зависимости от того что неверно - пароль, мейл или все сразу

**Comment by kavabunga** [comment]
Закрываем как больше не актуальное
