### ISSUE TITLE
[BUG] Форма авторизации - неверный текст ошибки, если поле Email оставить пустым

### ISSUE THREAD

**Issue by Xalgina** [Online-discount-card-service/odcs-frontend#296]
Шаги:

1. Перейти на https://skidivay.acceleratorpracticum.ru/
2. Нажать на кнопку "Войти"
3. Не заполнять поле Email
4. Заполнить поле Пароль 
5. Нажать на кнопку "Войти"

ОР: поле подсвечивается красным, под полем красным цветом выводится сообщение об ошибке "Укажите Email"
ФР: выводится сообщение об ошибке "Неверно указан Email"

Окружение:

Xiaomi Redmi 9, Android 11, разрешение экрана 393x873. Google Chrome 119.0.6045.163
iOS 16.6.1, iPhone 14, 390 × 844, Safari

![image](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/0786077b-5580-431c-93a2-255a17ece6a2)

![image](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/ab9d75e9-42da-46bc-a742-dbb9c8745580)

**Comment by kavabunga** [comment]
Актуальные требования: "Введите Email"
