### ISSUE TITLE
[BUG] Форма регистрации - спецсимволы не проходят валидацию в поле Имя

### ISSUE THREAD

**Issue by Xalgina** [Online-discount-card-service/odcs-frontend#301]
Шаги:

1. Перейти на https://skidivay.acceleratorpracticum.ru/
2. Нажать на кнопку "Войти"
3. Перейти во вкладку Регистрация
4. Заполнить поле Имя значением, содержащим спецсимволы

ОР: Поле Имя может содержать спецсимволы
ФР: спецсимволы не проходят валидацию в поле Имя

Окружение:
Xiaomi Redmi 9, Android 11, разрешение экрана 393x873. Google Chrome 119.0.6045.163
iOS 16.6.1, iPhone 14, 390 × 844, Safari

![image](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/37276771-3dd7-4b22-a821-9a46a728b540)

![image](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/d3f3a8bf-4db3-4570-8093-192a533113f4)

**Comment by Xalgina** [comment]
не валидируются символы №~` (с комп_клавиатуры)

**Comment by kavabunga** [comment]
Актуальные требования: 
Может содержать буквы A-Z, a-z, А-Я, а-я, Ёё, пробелы, символы @ ! # $ % & ' * + / = ? ^ _ ` { | } ~ - . 
(1-60 знаков)
Обязательное поле

**Comment by Xalgina** [comment]
в поле Имя не проходят валидацию два из перечисленных в таблице символов, а именно
~`
