### ISSUE TITLE
[BUG] Форма регистрации - некорректное сообщение об ошибке, если в поле Email ввести невалидные данные

### ISSUE THREAD

**Issue by Xalgina** [Online-discount-card-service/odcs-frontend#305]
Шаги:

1. Перейти на https://skidivay.acceleratorpracticum.ru/
2. Нажать на кнопку "Войти"
3. Перейти во вкладку Регистрация
4. Заполнить поле Email невалидными данными

ОР: При вводе невалидных данных в поле "Email" поле подсвечивается красным, выводится сообщение об ошибке "Введен некорректный Email"
ФР: Сообщение об ошибке - "Неверно указан Email"

Окружение:
Xiaomi Redmi 9, Android 11, разрешение экрана 393x873. Google Chrome 119.0.6045.163
iOS 16.6.1, iPhone 14, 390 × 844, Safari

![image](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/62ca2ffa-d5ef-4382-b64d-f23efa450ee6)

![image](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/486634ba-7c5b-405b-8499-c87bceab1f57)

**Comment by kavabunga** [comment]
Актуальные требования: "Введен некорректный Email"
