### ISSUE TITLE
[BUG] Форма регистрации - неверная максимальная длина строки в поле Пароль

### ISSUE THREAD

**Issue by Xalgina** [Online-discount-card-service/odcs-frontend#315]
Шаги:

1. Перейти на https://skidivay.acceleratorpracticum.ru/
2. Нажать на кнопку "Войти"
3. Перейти во вкладку Регистрация
4. Заполнить поле Пароль значением с количеством символов
- 128: Gjfklsdjlaejrмjejvk1Gjfklsdjlaejrмjejvk1Gjfklsdjlaejrмjejvk1Gjfklsdjlaejrмjejvk1Gjfklsdjlaejrмjejvk1Gjfklsdjlaejrмjejvk1Gjfkl123
- 127: Gjfklsdjlaejrмjejvk1Gjfklsdjlaejrмjejvk1Gjfklsdjlaejrмjejvk1Gjfklsdjlaejrмjejvk1Gjfklsdjlaejrмjejvk1Gjfklsdjlaejrмjejvk1Gjfkl12
- 20: Gjfklsdjlaejrмjejvk1
- 21: Gjfklsdjlaejrмjejvk12

ОР: Длина строки в поле Пароль от 8 до 128 символов
ФР: Длина строки от 8 до 20 символов. Начиная с 21 - не валидируется.

Окружение:
Xiaomi Redmi 9, Android 11, разрешение экрана 393x873. Google Chrome 119.0.6045.163
iOS 16.6.1, iPhone 14, 390 × 844, Safari

![image](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/01230b4a-f812-4256-9285-dd827124000e)

![image](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/832b24ef-95f2-4fc1-aa8a-ba5d2ea4a4c3)

**Comment by Xalgina** [comment]
Шаги:

1. Перейти на https://skidivay.acceleratorpracticum.ru/
2. Нажать на кнопку "Войти"
3. Перейти во вкладку Регистрация
4. Заполнить поле Пароль значением с очень большим количеством символов

ОР: Длина строки в поле Пароль от 8 до 256 символов
ФР: Максимальная длина строки - не ограничена. (Точнее, я ее не достигла. 3170 символов - валидируются)

Окружение:
Xiaomi Redmi 9, Android 11, разрешение экрана 393x873. Google Chrome 119.0.6045.163
iOS 16.6.1, iPhone 14, 390 × 844, Safari

![image](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/616ca571-f13e-4576-910a-2941077c75d1)
![image](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/6c82f25d-f823-496e-954d-2bcfb375a06a)

**Comment by kavabunga** [comment]
Gjfklsdjlaejrjejvk1Gjfklsdjlaejrjejvk1Gjfklsdjlaejrjejvk1Gjfklsdjlaejrjejvk1Gjfklsdjlaejrjejvk1Gjfklsdjlaejrjejvk1Gjfkl123dfkkjsfhdjskfhwehjhskdhfskfhsjfhskjdfhsfhsGjfklsdjlaejrjejvk1Gjfklsdjlaejrjejvk1Gjfklsdjlaejrjejvk1Gjfklsdjlaejrjejvk1Gjfklsdjlaejrjejvk1Gjfklsdjlaejrjejvk1Gjfkl123dfkkjsfhdjskfhwehjhskdhfskfhsjfhskjdfhsfhsGjfklsdjlaejrjejvk1Gjfklsdjlaejrjejvk1Gjfklsdjlaejrjejvk1Gjfklsdjlaejrjejvk1Gjfklsdjlaejrjejvk1Gjfklsdjlaejrjejvk1Gjfkl123dfkkjsfhdjskfhwehjhskdhfskfhsjfhskjdfhsfhs

Не проходит валидацию. Починили.
