### ISSUE TITLE
[BUG] Форма регистрации - спецсимволы "№;:/\'|{}~`., не проходят валидацию в поле Пароль

### ISSUE THREAD

**Issue by Xalgina** [Online-discount-card-service/odcs-frontend#338]
Шаги:

1. Перейти на https://skidivay.acceleratorpracticum.ru/
2. Нажать на кнопку "Войти"
3. Перейти во вкладку Регистрация
4. Заполнить поле Пароль значением, содержащим спецсимволы "№;:/\'|{}~`.,

ОР: Поле Пароль может содержать спецсимволы
ФР: Спецсимволы "№;:/\'|{}~`., не проходят валидацию в поле Пароль. Здесь перечислены символы, доступные с клавиатуры компьютера. 
В приложенном скринкасте список символов, которые не проходят валидацию и которые доступны ко вводу с клавиатуры смартфона, шире, плюс к тем, что выше еще ₽•√π÷×§∆£€$¢^°©®™✓.

Окружение:
Xiaomi Redmi 9, Android 11, разрешение экрана 393x873. Google Chrome 119.0.6045.163
iOS 16.6.1, iPhone 14, 390 × 844, Safari

![image](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/79a4b43a-e6c1-423d-b9ae-f3f4f9dcc597)

https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/1329dd1f-7750-433f-ad31-4b055e58ab78

**Comment by kavabunga** [comment]
По актуальным требованиям валидация проходит
