### ISSUE TITLE
[BUG] Неверный плейсхолдер и название поля с телефоном на экране восстановления пароля из формы авторизации

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/odcs-frontend#357]
Шаги:

Нажать на кнопку "Войти" на главном экране
Нажать на ссылку "Забыли пароль?" внизу формы авторизации

ОР: Плейсхолдер и название поля с телефоном "Телефон" на открывающемся экране для восстановления пароля из формы авторизации
ФР: Неверный плейсхолдер и название поля с телефоном "Номер телефона" на открывающемся экране для восстановления пароля из формы авторизации

![photo_2023-12-05_23-10-30](https://github.com/Online-discount-card-service/odcs-frontend/assets/148253752/7d3da470-58e6-40e2-88f7-5d4127eeb307)
![2023-12-05_23-04-10](https://github.com/Online-discount-card-service/odcs-frontend/assets/148253752/742b7748-7bd2-4add-95be-760a9fe3a57d)

**Comment by nasstea** [comment]
Не знаю, почему появился "мобильный", но должно быть одинаково, в макетах оставим просто "телефон"
