### ISSUE TITLE
[BUG] Неверная маска телефона в поле "Мобильный телефон" на экране восстановления пароля из формы авторизации

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/odcs-frontend#358]
Шаги:

Нажать на кнопку "Войти" на главном экране
Нажать на ссылку "Забыли пароль?" внизу формы авторизации

ОР: Маска телефона +7 (ХХХ) ХХХ-ХХ-ХХ в поле "Мобильный телефон" на открывающемся экране для восстановления пароля из формы авторизации
ФР: Неверная маска телефона +7 (ХХХ) ХХХ-99-99 в поле "Мобильный телефон" на открывающемся экране для восстановления пароля из формы авторизации

Окружение:
iOS 16.6.1, iPhone 14, 390 × 844, Safari

![photo_2023-12-05_23-10-31](https://github.com/Online-discount-card-service/odcs-frontend/assets/148253752/159d2768-ef21-4c8a-ab18-ac29f1c2a2ba)
![2023-12-05_23-04-10](https://github.com/Online-discount-card-service/odcs-frontend/assets/148253752/fcc342f8-0b5b-440d-8a8e-957f7fe98dd4)

**Comment by kavabunga** [comment]
Сверился с дизайном, там 99-99
