### ISSUE TITLE
Настроить максимальную длину инпутов

### ISSUE THREAD

**Issue by kolotilina-d** [Online-discount-card-service/odcs-frontend#391]
Вместо ошибки валидации ограничить максимальное количество символов в полях ввода

**Comment by kavabunga** [comment]
Нужно в компоненте Input в shared/ui добавить атрибут максимальной длины, пробросить его компоненту TextField который там рендерится и во всех формах для полей с ограничением этот атрибут задать. Где-то формы генерятся из массива объектов — там в атрибутах объектов можно указывать его, где-то сразу инпуты рендерятся — там соответственно в инпут сразу задавать.
