### ISSUE TITLE
[BUG] Экран смены почты после регистрации - нет текста сообщения, присутствует ненужный заголовок "Изменить почту". Неверный текст кнопки под полем "Email" - "Теперь верно". Есть кнопка "Назад" под хедером.

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/odcs-frontend#393]
Шаги:
Зарегистрироваться с валидными данными
Нажать на ссылку "Изменить почту"

ОР: Нет заголовка экрана, есть текст "Проверьте адрес, на который было отправлено письмо о подтверждении". Текст кнопки под полем "Email" - "Подтвердить". Нет кнопки "Назад" под хедером.
ФР: Нет текста сообщения, присутствует ненужный заголовок "Изменить почту". Неверный текст кнопки под полем "Email" - "Теперь верно". Есть кнопка "Назад" под хедером.

Окружение:
iOS 16.6.1, iPhone 14, 390 × 844, Safari

![photo_2023-12-09_00-44-36](https://github.com/Online-discount-card-service/odcs-frontend/assets/148253752/e7b07eb8-7e88-422d-9096-58ed7882d1e1)
![Снимок8](https://github.com/Online-discount-card-service/odcs-frontend/assets/148253752/e3fa7ea9-d08c-44ec-a0fe-d7e77d2efae8)

**Comment by kavabunga** [comment]
Вылечено
