### ISSUE TITLE
[BUG] Экран "Изменить пароль" по переходу из ЛК по ссылке - неверный вид хедера: по центру - лого, справа - крестик

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/odcs-frontend#414]
Шаги:
1. Войти под зарегистрированным пользователем
2. Нажать на иконку ЛК
3. Нажать на ссылку "Изменить пароль"
4. Нажать на кнопку "Не помню пароль"
5. В открывшемся модальном окне нажать на кнопку "Отправить"
6. Перейти по ссылке в письме

ОР: Экран "Изменить пароль" по переходу из ЛК по ссылке - в хедере слева - лого и "Скидывай", справа - иконка ЛК
ФР: Экран "Изменить пароль" по переходу из ЛК по ссылке - неверный вид хедера: по центру - лого, справа - крестик

Окружение:
iOS 16.6.1, iPhone 14, 390 × 844, Safari

![Снимок11](https://github.com/Online-discount-card-service/odcs-frontend/assets/148253752/3b82c8cd-46ac-49f3-a13d-e39a9ba0f536)
![Снимок10](https://github.com/Online-discount-card-service/odcs-frontend/assets/148253752/afa48ac8-8f80-4c25-8eba-d20408ccfaea)

**Comment by kavabunga** [comment]
Кажется, уже поменялся дизайн
