### ISSUE TITLE
[BUG] Удаление аккаунта - ошибка в тексте "Наша общение..." в обоих модальных окнах

### ISSUE THREAD

**Issue by Xalgina** [Online-discount-card-service/odcs-frontend#455]
Шаги:

1. Зарегистрировать пользователя
2. Перейти в Личный кабинет, Профиль
3. Нажать на кнопку "Удалить аккаунт" (здесь текст)
4. Нажать на кнопку "Да, все кончено" (здесь текст)

ОР:. Текст под заголовком "Вы уверены?" - "Наше общение было особенным и приносило радость..."
ФР:  Текст под заголовком "Вы уверены?" - "Наш**а** общение было особенным и приносило радость..."

Окружение:
Xiaomi Redmi 9, Android 11, разрешение экрана 393x873. Google Chrome 119.0.6045.163
iOS 16.6.1, iPhone 14, 390 × 844, Safari

![image](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/9e6c1d13-ccf6-4238-8614-3f0a6b0a23a6)
![image](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/bb853e90-ac61-4518-ae60-dfd4e79806fb)
![image](https://github.com/Online-discount-card-service/odcs-frontend/assets/148226806/582ddc56-6652-416f-8ffc-62f394ed77ff)

**Comment by kavabunga** [comment]
Извините я писать руский хорошо) Поправим
