### ISSUE TITLE
Главная страница в авторизованном состоянии (верстка)

### ISSUE THREAD

**Issue by kavabunga** [Online-discount-card-service/odcs-frontend#56]
- [ ] Состояние "Нет карт"
- [ ] Состояние "Есть карты"

![Image](https://github.com/Online-discount-card-service/odcs-frontend/assets/5512536/9f5ea46f-e188-49c1-837f-16121b34da48)

![Image](https://github.com/Online-discount-card-service/odcs-frontend/assets/5512536/52614668-72b9-467d-a779-79912810661b)

https://www.figma.com/file/3SieWKz3TaNqmqWhlz0dSt/Online-discount-card-service?type=design&node-id=741-6781&mode=dev

**Comment by HelgaMilne** [comment]
Сделано
