### ISSUE TITLE
Ссылка на logout внизу главной страницы (верстка)

### ISSUE THREAD

**Issue by kavabunga** [Online-discount-card-service/odcs-frontend#59]

**Comment by kavabunga** [comment]
![Image](https://github.com/Online-discount-card-service/odcs-frontend/assets/5512536/a03c91a3-5d3c-49fe-be1f-3703659eccbb)



https://www.figma.com/file/3SieWKz3TaNqmqWhlz0dSt/Online-discount-card-service?type=design&node-id=1359-3940&mode=dev

**Comment by HelgaMilne** [comment]
Ссылка добавлена.
